### ISSUE TITLE
Rewrite Sniffator example app using latest version of library.

### ISSUE THREAD

**Issue by Cierpliwy** [Polidea/react-native-ble-plx#189]
- [x] Remove old Sniffator application (#190)
- [x] Create new Sniffator application which reuses identifiers and certificates from previous one. (#190)
- [ ] Add implementation of BLE actions which are implemented using redux-saga/redux-thunk (#192)
- [ ] Create screen hierarchy using standard components or react-navigation library.
- [ ] Implement scanning screen
- [ ] Implement service/characteristic browser screen
- [ ] Implement characteristic details screen

**Comment by pstanton** [comment]
i would also suggest a simpler 'getting started' example which doesn't use any optional dependencies such as redux.

**Comment by lefoy** [comment]
Any update on the example app?
